theme: jekyll-theme-cayman
title: "いんたぽスプライト.anm"
description: "Aviutl＆拡張編集 アニメーション効果フィルタ用スクリプト（暫定版）"
show_downloads: false

twitter:
  username: tiribro

author:
  twitter_link: "https://twitter.com/tiribro"
  twitter_name: "チリブロッコ"

github:
  is_project_page: false
  zip_url: "https://github.com/tiribro/InterpoSprite.anm/releases/download/v0.0/InterpoSprite.zip"
  youtube_demo_url: "https://www.youtube.com/embed/lwqTDRHcOpo"
  gslide_tutorial_url: "https://docs.google.com/presentation/d/e/2PACX-1vSvLXyXthbdOlZ7u8e6vzR8amaa4_3D-MEip6eq-rIhg_oDipwgQg0cpBh6Z9KHgRYB1r1X-UEHQQ0A/embed?start=false&loop=true&delayms=3000"

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
